[package]
cairo-version = "2.6.3"
name = "Rock Paper Scissors"
version = "0.7.0"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate apply"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.7.0" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.world]
name = "Rock Paper Scissors"
description = "Rock Paper Scissors game onchain"
